# Generated by Django 4.2.1 on 2024-07-17 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('addr_line1', models.CharField(max_length=50)),
                ('addr_line2', models.CharField(blank=True, max_length=50, null=True)),
                ('addr_line3', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(max_length=50)),
                ('eir_code', models.CharField(max_length=50)),
                ('county', models.CharField(max_length=50)),
                ('country', models.CharField(choices=[('IE', 'Ireland')], default='IE', max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_nr', models.CharField(max_length=50)),
                ('default_addr', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Addresses',
                'ordering': ['county', 'city'],
            },
        ),
    ]
