# Generated by Django 4.2.1 on 2024-07-14 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('addr_line1', models.CharField(max_length=50)),
                ('addr_line2', models.CharField(blank=True, max_length=50, null=True)),
                ('addr_line3', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(max_length=50)),
                ('eir_code', models.CharField(max_length=50)),
                ('county', models.CharField(max_length=50)),
                ('country', models.CharField(choices=[('IE', 'Ireland')], default='IE', max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_nr', models.IntegerField()),
                ('default_addr', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Addresses',
                'ordering': ['county', 'city'],
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_dt', models.DateTimeField(auto_now_add=True)),
                ('order_note', models.TextField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=6)),
                ('shipping_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('purchaser_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('PEND', 'Pending'), ('PROC', 'Processing'), ('RDY', 'Ready to Ship'), ('SHP', 'Shipped'), ('DLV', 'Delivered')], default='PEND', max_length=50)),
                ('tracking_link', models.TextField(blank=True, null=True)),
                ('stripe_pid', models.CharField(max_length=254)),
                ('billing_addr', models.ForeignKey(on_delete=models.SET('0'), related_name='billing_addr', to='profiles.addresses')),
                ('purchaser', models.ForeignKey(blank=True, null=True, on_delete=models.SET('0'), to=settings.AUTH_USER_MODEL)),
                ('shipping_addr', models.ForeignKey(on_delete=models.SET('0'), related_name='shipping_addr', to='profiles.addresses')),
            ],
            options={
                'verbose_name_plural': 'Order Histories',
                'ordering': ['-order_dt', 'status'],
            },
        ),
        migrations.CreateModel(
            name='SavedItems',
            fields=[
                ('list_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('list_type', models.CharField(choices=[('CART', 'Cart'), ('WATCH', 'Watchlist'), ('SAVED', 'Saved List')], max_length=50)),
                ('expected_dt', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=models.SET('0'), to='products.productdetails')),
            ],
            options={
                'verbose_name_plural': 'Saved Items',
                'ordering': ['list_type', 'product'],
            },
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('purchase_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profiles.orderhistory')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.productdetails')),
            ],
            options={
                'verbose_name_plural': 'Purchases',
                'ordering': ['-purchase_id', 'product'],
            },
        ),
    ]
