# Generated by Django 4.2.1 on 2024-07-15 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_uuid', models.CharField(editable=False, max_length=32, unique=True)),
                ('news_email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
