# Generated by Django 4.2.1 on 2024-06-26 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productdetails'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedItems',
            fields=[
                ('list_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('list_type', models.CharField(choices=[('CART', 'Cart'), ('WATCH', 'Watchlist'), ('SAVED', 'Saved List')], max_length=50)),
                ('expected_dt', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=models.SET('0'), to='products.productdetails')),
            ],
            options={
                'verbose_name_plural': 'Saved Items',
                'ordering': ['list_type', 'product'],
            },
        ),
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('addr_line1', models.CharField(max_length=50)),
                ('addr_line2', models.CharField(blank=True, max_length=50, null=True)),
                ('addr_line3', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(max_length=50)),
                ('eir_code', models.CharField(max_length=50)),
                ('county', models.CharField(max_length=50)),
                ('country', models.CharField(choices=[('IE', 'Ireland')], default='IE', max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_nr', models.IntegerField()),
                ('default_addr', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Addresses',
                'ordering': ['county', 'city'],
            },
        ),
    ]
