# Generated by Django 4.2.1 on 2024-07-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='phone_nr',
            field=models.CharField(max_length=50),
        ),
    ]
