# Generated by Django 4.2.1 on 2024-07-17 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_addresses_phone_nr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderhistory',
            name='billing_addr',
        ),
        migrations.RemoveField(
            model_name='orderhistory',
            name='purchaser',
        ),
        migrations.RemoveField(
            model_name='orderhistory',
            name='shipping_addr',
        ),
        migrations.RemoveField(
            model_name='purchases',
            name='order',
        ),
        migrations.RemoveField(
            model_name='purchases',
            name='product',
        ),
        migrations.RemoveField(
            model_name='saveditems',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='saveditems',
            name='product',
        ),
        migrations.DeleteModel(
            name='Addresses',
        ),
        migrations.DeleteModel(
            name='OrderHistory',
        ),
        migrations.DeleteModel(
            name='Purchases',
        ),
        migrations.DeleteModel(
            name='SavedItems',
        ),
    ]
