# Generated by Django 4.2.1 on 2024-06-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_orderhistory_purchases'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='order_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
