# Generated by Django 4.2.1 on 2024-06-30 13:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_addresses_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='purchaser',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('0'), to=settings.AUTH_USER_MODEL),
        ),
    ]
