# Generated by Django 4.2.1 on 2024-06-30 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_orderhistory_purchaser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderhistory',
            old_name='total_cost',
            new_name='subtotalt',
        ),
    ]
