# Generated by Django 4.2.1 on 2024-06-30 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_rename_total_cost_orderhistory_subtotalt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderhistory',
            old_name='subtotalt',
            new_name='subtotal',
        ),
    ]
