# Generated by Django 4.2.1 on 2024-06-30 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_rename_subtotalt_orderhistory_subtotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderhistory',
            name='payment_type',
        ),
    ]
