# Generated by Django 4.2.1 on 2024-06-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_remove_orderhistory_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='purchaser_email',
            field=models.EmailField(default='Test@test.com', max_length=254),
            preserve_default=False,
        ),
    ]
