# Generated by Django 4.2.1 on 2024-07-01 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_orderhistory_purchaser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='phone_nr',
            field=models.IntegerField(max_length=15),
        ),
    ]
