# Generated by Django 4.2.1 on 2024-07-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_alter_addresses_phone_nr'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=6),
            preserve_default=False,
        ),
    ]
