# Generated by Django 4.2.1 on 2024-07-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_orderhistory_grand_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='stripe_pid',
            field=models.CharField(default='', max_length=254),
        ),
    ]
