# Generated by Django 4.2.1 on 2024-07-07 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_productdetails_product'),
        ('profiles', '0017_orderhistory_stripe_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profiles.orderhistory'),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.productdetails'),
        ),
    ]
