# Generated by Django 4.2.1 on 2024-07-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_alter_purchases_order_alter_purchases_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='stripe_pid',
            field=models.CharField(max_length=254),
        ),
    ]
