# Generated by Django 4.2.1 on 2024-07-09 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_alter_orderhistory_stripe_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='billing_addr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_addr', to='profiles.addresses'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='shipping_addr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipping_addr', to='profiles.addresses'),
        ),
    ]
