# Generated by Django 4.2.1 on 2024-07-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_alter_orderhistory_billing_addr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='billing_addr',
            field=models.ForeignKey(on_delete=models.SET('0'), related_name='billing_addr', to='profiles.addresses'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='shipping_addr',
            field=models.ForeignKey(on_delete=models.SET('0'), related_name='shipping_addr', to='profiles.addresses'),
        ),
    ]
