# Generated by Django 4.2.1 on 2024-07-17 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedItems',
            fields=[
                ('list_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('list_type', models.CharField(choices=[('CART', 'Cart'), ('WATCH', 'Watchlist'), ('SAVED', 'Saved List')], max_length=50)),
                ('expected_dt', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=models.SET('0'), to='products.productdetails')),
            ],
            options={
                'verbose_name_plural': 'Saved Items',
                'ordering': ['list_type', 'product'],
            },
        ),
    ]
