# Generated by Django 4.2.1 on 2024-07-17 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('addresses', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_dt', models.DateTimeField(auto_now_add=True)),
                ('order_note', models.TextField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=6)),
                ('shipping_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('purchaser_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('PEND', 'Pending'), ('PROC', 'Processing'), ('RDY', 'Ready to Ship'), ('SHP', 'Shipped'), ('DLV', 'Delivered')], default='PEND', max_length=50)),
                ('tracking_link', models.TextField(blank=True, null=True)),
                ('stripe_pid', models.CharField(max_length=254)),
                ('billing_addr', models.ForeignKey(on_delete=models.SET('0'), related_name='billing_addr', to='addresses.addresses')),
                ('purchaser', models.ForeignKey(blank=True, null=True, on_delete=models.SET('0'), to=settings.AUTH_USER_MODEL)),
                ('shipping_addr', models.ForeignKey(on_delete=models.SET('0'), related_name='shipping_addr', to='addresses.addresses')),
            ],
            options={
                'verbose_name_plural': 'Order Histories',
                'ordering': ['-order_dt', 'status'],
            },
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('purchase_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='checkout.orderhistory')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.productdetails')),
            ],
            options={
                'verbose_name_plural': 'Purchases',
                'ordering': ['-purchase_id', 'product'],
            },
        ),
    ]
