# Generated by Django 4.2.1 on 2024-04-24 14:04

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutriforce_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('product_pic', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('price', models.IntegerField()),
                ('size', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('stock_count', models.IntegerField()),
                ('ingredients', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('related_products', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-active', 'product_name'],
            },
        ),
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('addr_line_1', models.CharField(max_length=50)),
                ('addr_line_2', models.CharField(blank=True, max_length=50, null=True)),
                ('addr_line_3', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(max_length=50)),
                ('eir_code', models.CharField(max_length=50)),
                ('county', models.CharField(max_length=50)),
                ('country', models.CharField(default='Ireland', max_length=50)),
                ('phone_nr', models.IntegerField()),
                ('default_addr', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['county', 'city'],
            },
        ),
    ]
