# Generated by Django 4.2.1 on 2024-04-24 14:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutriforce_app', '0002_products_addresses'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseHistory',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_dt', models.DateTimeField(auto_now_add=True)),
                ('payment_type', models.CharField(choices=[('VISA', 'Visa'), ('MC', 'mastercard'), ('PP', 'PayPal'), ('GP', 'GooglePay'), ('AP', 'ApplePay')], max_length=50)),
                ('status', models.CharField(choices=[('PEND', 'Pending'), ('PROC', 'Processing'), ('RDY', 'Ready to Ship'), ('SHP', 'Shipped'), ('DLV', 'Delivered')], default='PEND', max_length=50)),
                ('tracking_link', models.TextField(blank=True, null=True)),
                ('billing_addr', models.ForeignKey(on_delete=models.SET('deleted_user'), related_name='billing_addr', to='nutriforce_app.addresses')),
                ('purchaser', models.ForeignKey(on_delete=models.SET('deleted_user'), to=settings.AUTH_USER_MODEL)),
                ('shipping_addr', models.ForeignKey(on_delete=models.SET('deleted_user'), related_name='shipping_addr', to='nutriforce_app.addresses')),
            ],
            options={
                'ordering': ['-order_dt', 'status'],
            },
        ),
    ]
