# Generated by Django 4.2.1 on 2024-04-24 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutriforce_app', '0003_purchasehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedItems',
            fields=[
                ('list_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('list_type', models.CharField(choices=[('CART', 'Cart'), ('WATCH', 'Watchlist'), ('SAVED', 'Saved List')], max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=models.SET('deleted_product'), to='nutriforce_app.products')),
            ],
            options={
                'ordering': ['list_type', 'product'],
            },
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('purchase_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='nutriforce_app.purchasehistory')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='nutriforce_app.products')),
            ],
            options={
                'ordering': ['-purchase_id', 'product'],
            },
        ),
    ]
