# Generated by Django 4.2.1 on 2024-04-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutriforce_app', '0005_remove_user_first_name_remove_user_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='related_products',
            new_name='categories',
        ),
        migrations.AddField(
            model_name='saveditems',
            name='expected_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
