# Generated by Django 4.2.1 on 2024-05-01 15:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nutriforce_app', '0007_alter_products_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='created_ts',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
