# Generated by Django 4.2.1 on 2024-05-01 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutriforce_app', '0008_products_created_ts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addresses',
            options={'ordering': ['county', 'city'], 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['-active', 'product_name'], 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='purchasehistory',
            options={'ordering': ['-order_dt', 'status'], 'verbose_name_plural': 'Purchase Histories'},
        ),
        migrations.AlterModelOptions(
            name='purchases',
            options={'ordering': ['-purchase_id', 'product'], 'verbose_name_plural': 'Purchases'},
        ),
        migrations.AlterModelOptions(
            name='saveditems',
            options={'ordering': ['list_type', 'product'], 'verbose_name_plural': 'Saved Items'},
        ),
    ]
