# Generated by Django 4.2.1 on 2024-05-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutriforce_app', '0011_alter_addresses_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='country',
            field=models.CharField(choices=[('IE', 'Ireland')], default='IE', max_length=50),
        ),
    ]
