# Generated by Django 4.2.1 on 2024-05-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutriforce_app', '0012_alter_addresses_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasehistory',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=4.99, max_digits=6),
            preserve_default=False,
        ),
    ]
