# Generated by Django 4.2.1 on 2024-05-26 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutriforce_app', '0015_alter_purchasehistory_billing_addr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='flavours',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
