# Generated by Django 4.2.1 on 2024-05-27 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutriforce_app', '0018_products_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='flavours',
        ),
        migrations.RemoveField(
            model_name='products',
            name='sizes',
        ),
        migrations.CreateModel(
            name='ProductColourFlavours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sizes', models.CharField(max_length=500)),
                ('flavours', models.CharField(blank=True, max_length=600, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutriforce_app.products')),
            ],
        ),
    ]
