# Generated by Django 4.2.1 on 2024-05-27 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutriforce_app', '0019_remove_products_flavours_remove_products_sizes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcolourflavours',
            old_name='flavours',
            new_name='flavour',
        ),
        migrations.RenameField(
            model_name='productcolourflavours',
            old_name='sizes',
            new_name='size',
        ),
    ]
