# Generated by Django 4.2.1 on 2024-05-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutriforce_app', '0021_productdetails_alter_products_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='size_unit',
            field=models.CharField(default='change', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='size',
            field=models.IntegerField(),
        ),
    ]
