# Generated by Django 4.2.1 on 2024-06-18 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutriforce_app', '0022_productdetails_size_unit_alter_productdetails_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='nutriforce_app.productdetails'),
        ),
        migrations.AlterField(
            model_name='saveditems',
            name='product',
            field=models.ForeignKey(on_delete=models.SET('0'), to='nutriforce_app.productdetails'),
        ),
    ]
