# Generated by Django 4.2.1 on 2024-06-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutriforce_app', '0023_alter_purchases_product_alter_saveditems_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasehistory',
            name='order_number',
            field=models.CharField(default='Z', editable=False, max_length=32, unique=True),
            preserve_default=False,
        ),
    ]
