# Generated by Django 4.2.1 on 2024-06-23 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutriforce_app', '0024_purchasehistory_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='order_purchases', to='nutriforce_app.purchasehistory'),
        ),
    ]
