# Generated by Django 4.2.1 on 2024-06-23 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutriforce_app', '0025_alter_purchases_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PurchaseHistory',
            new_name='OrderHistory',
        ),
        migrations.AlterModelOptions(
            name='orderhistory',
            options={'ordering': ['-order_dt', 'status'], 'verbose_name_plural': 'Order Histories'},
        ),
    ]
