# Generated by Django 4.2.1 on 2024-06-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutriforce_app', '0026_rename_purchasehistory_orderhistory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addresses',
            old_name='addr_line_1',
            new_name='addr_line1',
        ),
        migrations.RenameField(
            model_name='addresses',
            old_name='addr_line_2',
            new_name='addr_line2',
        ),
        migrations.RenameField(
            model_name='addresses',
            old_name='addr_line_3',
            new_name='addr_line3',
        ),
        migrations.AddField(
            model_name='addresses',
            name='email',
            field=models.EmailField(default='crazycooky_77@yahoo.ca', max_length=254),
            preserve_default=False,
        ),
    ]
