# Generated by Django 4.2.1 on 2024-07-14 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=50)),
                ('product_pic_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('product_pic', models.ImageField(blank=True, default='products/default_img.jpeg', null=True, upload_to='')),
                ('description', models.TextField()),
                ('main_cat', models.CharField(choices=[('SPORTS', 'Sports'), ('HEALTH', 'Health')], max_length=50)),
                ('categories', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Products',
                'ordering': ['product_name'],
            },
        ),
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_sale', models.BooleanField(default=False)),
                ('size', models.IntegerField()),
                ('size_unit', models.CharField(max_length=50)),
                ('flavour', models.CharField(blank=True, max_length=600, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('stock_count', models.IntegerField()),
                ('ingredients', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.products')),
            ],
            options={
                'verbose_name_plural': 'Product Details',
                'ordering': ['product__product_id'],
            },
        ),
    ]
