# Generated by Django 4.2.1 on 2024-06-26 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('size_unit', models.CharField(max_length=50)),
                ('flavour', models.CharField(blank=True, max_length=600, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('stock_count', models.IntegerField()),
                ('ingredients', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
            options={
                'verbose_name_plural': 'Product Details',
                'ordering': ['product__product_id'],
            },
        ),
    ]
