# Generated by Django 4.2.1 on 2024-06-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_main_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='on_sale',
            field=models.BooleanField(default=False),
        ),
    ]
