# Generated by Django 4.2.1 on 2024-06-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productdetails_on_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='size',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
