# Generated by Django 4.2.1 on 2024-06-26 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_productdetails_options_alter_products_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productdetails',
            options={'ordering': ['product__product_id'], 'verbose_name_plural': 'Product Details'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['product_name'], 'verbose_name_plural': 'Products'},
        ),
    ]
