# Generated by Django 4.2.1 on 2024-07-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_productdetails_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_pic_url',
            field=models.URLField(default='0', max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='product_pic',
            field=models.ImageField(upload_to=''),
        ),
    ]
