# Generated by Django 4.2.1 on 2024-07-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_products_product_pic_url_alter_products_product_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_pic_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
