# Generated by Django 4.2.1 on 2024-07-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_products_product_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_pic',
            field=models.ImageField(blank=True, default='/media/default_img.jpeg', null=True, upload_to=''),
        ),
    ]
