# Generated by Django 4.2.1 on 2024-07-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_products_product_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_pic',
            field=models.ImageField(blank=True, default='products/default_img.jpeg', null=True, upload_to=''),
        ),
    ]
